namespace AlphaMDHealth.Utility;

public enum AppPermissions 
{
	NavigationComponent,
	LoginView,
	SetNewPasswordView,
	RegistrationView,
	ForgotPasswordView,
	SMSAuthenticationView,
	PinCodeView,
	PincodeLoginView,
	LandingView,
	ChangePasswordView,
	ResetPasswordView,
	Logout,
	ChangePincodeView,
	SampleCodesView, //todo: to remove
    SampleCodeAddEdit, //todo: to remove

    DashboardView,
	DashboardAddEdit,
	DashboardConfigurationView,
	DashboardConfigurationAddEdit,
	DashboardConfigurationDelete,

	OrganisationSetup,
	OrganisationTabView,
	OrganisationView,
	OrganisationAddEdit,
	OrganisationDelete,
	OrganisationContactsView,
	OrganisationContactAddEdit,
	OrganisationContactDelete,

	OrganisationSettingsView,
	OrganisationSettingsAddEdit,
	OrganisationThemeSettingsView,
	OrganisationThemeSettingsAddEdit,

	OrganisationTagsView,
    OrganisationTagAddEdit,
    OrganisationTagDelete,

    BranchTabView,
	BranchesView,
	BranchView,
	BranchAddEdit,
	BranchDelete,
	BranchContactsView,
	BranchContactAddEdit,
	BranchContactDelete,

	DepartmentsView,
	DepartmentAddEdit,
	DepartmentDelete,

	BillingItemsView,
	BillingItemAddEdit,
	BillingItemDelete,

	PaymentModesView,
	PaymentModeAddEdit,
	PaymentModeDelete,

	ReasonsView,
	ReasonAddEdit,
	ReasonDelete,

	ProfileView,
	ProfileAddEdit,
	MultipleUsersView,
	UsersView,
	UserView,
	UserAddEdit,
	UserDelete,
	UserResendActivation,
	UserContactsView,
	UserContactAddEdit,
	UserContactDelete,
	UserTabView,
	PatientsView,
	PatientAddEdit,
	PatientDelete,
	PatientContactsView,
	PatientContactAddEdit,
	PatientContactDelete,
	PatientTabView,
	PatientView,
	PatientPage,
	PatientDetailsView,
	PatientDetailView,
	AddBulkUploadUserView,
	AddBulkUploadPatients,


	CarepathsView,
	CarepathAddEdit,
	CarepathDelete,
	QuestionnairesTabView,
	QuestionnairesView,
	QuestionnairePublish,
	QuestionnaireAddEdit,
	QuestionnaireDelete,
	QuestionsView,
	QuestionAddEdit,
	QuestionDelete,
	QuestionnaireQuestionsView,
	QuestionnaireQuestionAddEdit,
	QuestionnaireQuestionDelete,
	SubscalesView,
	SubscalesScoreView,
	SubscaleAddEdit,
	SubscaleScoreView,
	SubscaleDelete,
	QuestionScoresView,
	QuestionScoreAddEdit,
	QuestionScoreDelete,
	QuestionnaireTaskView,
	CaregiversView,
	CaregiverAddEdit,
	CaregiverDelete,

    //ReadingTypesView,
    //ReadingTypeAddEdit,
    //ReadingTypeDelete,
    //ReadingsView,
    //ReadingAddEdit,
    //ReadingDelete,
    //ReadingUnitsView,
    //ReadingUnitAddEdit,
    //ReadingUnitDelete,
    ReadingScanVitals,
    ReadingResults,

    ProgramReadingRangesView,
	ProgramReadingRangeAddEdit,
	ProgramReadingRangeDelete,
	PatientReadingTargetAddEdit,
	PatientReadingsView,
	PatientReadingAddEdit,
	PatientReadingDelete,
	PatientReadingDetailsView,

	EducationsView,
	EducationAddEdit,
	EducationPublish,
	PatientEducationAddEdit,
    PatientEducationDelete,
    EducationPreview,
	PatientEducationsView,
	MyEducationsView,

	PatientFilesView,
	PatientFileAddEdit,
	PatientFileDelete,

    PatientScanHistoryView,

    ChatsView,
	ChatAddEdit,
	NewChatView,
	ChatDelete,
	ChatView,

	MasterDataView,
	SubscriptionPlansView,
	SubscriptionPlanAddEdit,
	SubscriptionPlanDelete,
    BuySubscriptionPlan, 

    ConfigureContentsView,
	StaticContentsView,
	StaticContentAddEdit,
	StaticContentDelete,
	StaticContentPublish,
	WebGroupContentsView,
	WebGroupContentAddEdit,
	WebGroupContentDelete,
	WebMenusView,
	WebMenuAddEdit,
	WebMenuDelete,
	MobileMenuNodesView,
	MobileMenuNodeAddEdit,
	MobileMenuNodeDelete,
	MobileMenuGroupsView,
	MobileMenuGroupAddEdit,
	MobileMenuGroupDelete,
	CollapsableMenusView,

	MobileMenusView,
	MobileMenuAddEdit,
	MobileMenuDelete,

	PatientMobileMenusView,
	PatientMobileMenuAddEdit,
	PatientMobileMenuDelete,

	ProfessionsView,
	ProfessionAddEdit,
	ProfessionDelete,

	Appointments,
	AppointmentsView,
	AppointmentView,
	AppointmentAddEdit,
	AppointmentCancelMeeting,
	AppointmentDecline,
	AppointmentJoin,
	VideoCallingView,
	PatientAppointmentsView,

	InstructionsView,
	InstructionAddEdit,
	InstructionDelete,
	SubflowsView,
	SubflowAddEdit,
	SubflowDelete,
	TasksView,
	TaskAddEdit,
	TaskDelete,
	ProgramsView,
	ProgramAddEdit,
	ProgramPublish,
	ProgramCaregiversView,
	ProgramCaregiverAddEdit,
	ProgramCaregiverDelete,
	ProgramReadingsView,
	ProgramReadingAddEdit,
	ProgramReadingDelete,
	PatientProgramsView,
	PatientProgramAddEdit,
	PatientProgramDelete,
	ProgramEducationsView,
	ProgramEducationAddEdit,
	ProgramEducationDelete,
	ProgramSubscribeView,
	ProgramMedicationsView,
	ProgramMedicationAddEdit,
	ProgramMedicationDelete,

	PatientBillsView,
	PatientBillAddEdit,
	PatientBillDelete,
	PatientBillShare,
	PatientBillDetailsView,

	ProgramBillingItemsView,
	ProgramBillingItemAddEdit,
	ProgramBillingItemDelete,

	EducationCategoriesView,
	EducationCategoryAddEdit,
	EducationCategoryDelete,

	FilesCategoriesView,
	FileCategoryAddEdit,
	FileCategoryDelete,

	ConsentsView,
	ConsentAddEdit,
	ConsentDelete,
	UserConsentsView,
	StaticMessageView,

	RegisterPasswordView,
	PatientTasksView,
	PatientAssignTaskView,
	PatientTaskView,
	PatientTaskDelete,
	PatientTaskStatusEdit,

	DynamicLinkPage,
	UserAccountSettingsView,
    PatientMobileMenuView,


    SupportedDevicesView,

	PatientMedicationsView,
	PatientMedicationAddEdit,
	PatientMedicationDelete,
	PrescriptionView,
	PrescriptionShare,

	WelcomeScreensView,
	WelcomeScreenAddEdit,
	WelcomeScreenDelete,
    UserWelcomeScreensView,

    ProgramTrackersView,
	ProgramTrackerAddEdit,
	ProgramTrackerDelete,

	PatientTrackersView,
	PatientTrackerDetailView,
	PatientTrackerAddEdit,
	PatientTrackerDelete,

	ManageOrganisationsView,
	ManageOrganisationView,

	PatientProviderNoteTypesView,
	PatientProviderNoteTypeAddEdit,
	PatientProviderNoteTypeDelete,

	PatientProviderNotesView,
	PatientProviderNoteAddEdit,
	PatientProviderNoteDelete,

	TrackersView,
	TrackersAddEdit,
	TrackerDelete,
	TrackerRangesView,
	TrackerRangesAddEdit,
	TrackerRangesDelete,

	ProgramConfigurationView,

	BillingReportsView,

	ProgramReasonsView,
	ProgramReasonAddEdit,
	ProgramReasonDelete,
	ShareProfileAddEdit,
	ShareProfileDelete,
	ShareProfilesView,

	MedicalHistoryView,
	MedicalHistoryAddEdit,
	MedicalHistoryPrint,
	MedicalHistoryShare,

	LinkedUsersView,
	LinkedUserAddEdit,
	LinkedUserDelete,

    HealthScansView,
    CreditHistoryView,
    CreditAddEdit,
    ScansHistoryView,

    LanguageSelectionView,

    ProgramTasksView,
    ProgramTaskAddEdit,
    ProgramTaskDelete,

	ProgramServicesView,
	ProgramServiceAddEdit,
	ProgramServiceDelete,

	ProgramScansView,
	ProgramScanAddEdit,
}