namespace AlphaMDHealth.Utility;

public enum DataSyncFor
{
    Defaults = 0,
    MasterData = 1, //FirstLaunchMasterData = 1, // First time initialization
    MasterDataI18N = 2, // After language selection
    UserData = 3, // User data
    UserDataI18N = 4, // After language change
    UserDataBatch1 = 5, // User data
    UserDataBatch1I18N = 6, // After language change
    UserDataBatch2 = 7, // User data
    UserDataBatch2I18N = 8, // After language change
    UserDataBatch3 = 9, // User data
    UserDataBatch3I18N = 10, // After language change
    UserDataBatch4 = 11, // User data
    UserDataBatch4I18N = 12, // After language change 

    AppIntros,
    AppointmentDetails,
    Appointments,
    BillingItems,
    BillingItemsI18N,
    Chats,
    Consents,
    Contacts,
    Countries,
    DashboardConfigurations,
    EducationCategories,
    EducationDetails,
    Educations,
    ErrorLogs,
    FeatureRelations,
    Features,
    FileCategories,
    FileCategoryDetails,
    Files,
    InstructionI18N,
    Instructions,
    Languages,
    Medicines,
    MenuGroups,
    Menus,
    OrganisationBranchesDepartments,
    OrganisationReadingDevices,
    Pages,
    PatientBills,
    PatientContactDetails,
    PatientContacts,
    PatientMedications,
    PatientPrograms,
    PatientProviderNotes,
    PatientReadings,
    PatientsSharedPrograms,
    PatientTargets,
    PatientTasks,
    PatientTrackerDetails,
    PatientTrackers,
    PaymentModes,
    PaymentModesI18N,
    Professions,
    ProgramBillingItems,
    ProgramCaregivers,
    ProgramNotes,
    ProgramNotesI18N,
    Programs,
    ProgramTrackers,
    QuestionnaireI18N,
    Questionnaires,
    ReadingMasters,
    Readings,
    Resources,
    Roles,
    SampleData, //todo: to remove
    Settings,
    Trackers,
    TrackersI18N,
    Units,
    UnitsI18N,
    UserAccountSettings,
    UserConsents,
    Users,

    ReadingsFromOtherApps,
    Height,
    Weight,
    HeartRate,
    HbA1c,
    BloodPressure,
    BloodGlucose,
    Hydration,
    NutritionSodium,
    NutritionSugar,
    NutritionTotalCarbs,
    NutritionTotalFat,
    NutritionVitaminA,
    NutritionVitaminC,
    NutritionProtein,
    NutritionPotassium,
    NutritionCalcium,
    NutritionCalories,
    NutritionCholesterol,
    NutritionDietaryFiber,
    NutritionIron,
    SpO2,
    Steps,
    BodyTemperature,
    Badminton,
    Boxing,
    Climbing,
    Crossfit,
    Bicycling,
    Dancing,
    StrengthTraining,
    Gymnastics,
    MartialArts,
    Cardio,
    Running,
    Skating,
    Soccer,
    Squash,
    Swimming,
    Walking,
    Yoga,
    HighIntensityIntervalTraining,
    JumpRope,
    Kickboxing,
    Pilates,
    StairClimbing,
}